### ISSUE TITLE
Page not opening

### ISSUE THREAD

**Issue by okangalfred** [Maaacoooo/STIVoting17#2]
Please i add the following errors when trying it
1. Page not found when candidate is trying to view result.
2. When i click the Generate button in Voting Passes, nothing opens/occurs
3. When i click on Clear Votes in Settings, nothing opens/occurs
4. When i click on Reset to Default in settings, nothing opens/occurs

**Comment by Maaacoooo** [comment]
Updated. Thanks

**Comment by rduhn** [comment]
Still not working. Generate passes,  Clear Votes and Reset to default not working please. As of 07 August 2018
